version: "3"

services:
  app:
    container_name: django-poc-app
    image: django-poc-app
    build: 
      context: ./
      dockerfile: app.Dockerfile
    restart: always
    ports:
      - "8081:8080"
    environment:
      DB_NAME: localdb
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: django
      DB_PASSWORD: django
      DJANGO_SETTINGS_MODULE: app.settings
    depends_on:
      - db

  api:
    container_name: django-poc-api
    image: django-poc-api
    build: 
      context: ./
      dockerfile: api.Dockerfile
    restart: always
    ports:
      - "8082:8080"
    environment:
      DB_NAME: localdb
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: django
      DB_PASSWORD: django
      DJANGO_SETTINGS_MODULE: app.settings
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: localdb
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
