services:
  registry-db:
    image: postgres:13
    container_name: registry_db
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: registry
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metadata
    volumes:
      - mlflow_data:/var/lib/postgresql/data/

#  mlflow:
#    image: mlflow
#    container_name: mlflow
#    build:
#      context: .
#      dockerfile: mlflow.Dockerfile
#    restart: always
#    user: "1000"
#    expose:
#      - 5000
#    ports:
#      - "5000:5000"
#    depends_on:
#      - registry-db
#    environment:
#      MLFLOW_TRACKING_SERVER_HOST: 0.0.0.0
#      MLFLOW_TRACKING_SERVER_PORT: 5000
#      MLFLOW_ARTIFACT_STORE: /mlflow/artifacts
#      MLFLOW_BACKEND_STORE: registry-db
#      POSTGRES_USER: registry
#      POSTGRES_PASSWORD: password
#      POSTGRES_DATABASE: metadata
#      POSTGRES_PORT: 5432
#      WAIT_FOR_IT_TIMEOUT: 60
#    volumes:
#      - ../registry/artifacts:/mlflow/artifacts

volumes:
  mlflow_data:
